myenv:
  compiler:
  - toolchain: gcc
    spec: gcc
  specs:
  - icon4py@icon_20250328 +distributed +cuda
  - py-mpi4py
  - python
  unify: true
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    default:
